#+title: Introspectio(n)
#+author:
#+language: en
#+startup: overview
#+options: toc:nil html-postamble:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/nix.css">

[[file:../index.html][Home]]   ✾   [[file:../about.html][About]]

* Introspection 1  

First, believe in yourself. Remember that you are building a future and be part of an organization that's going to shape the way people all live, and think that, “If someone can be part of 1%, you can too.” whether the path ahead seems crumbling, challenging, or even the ground cracks open, or rocks fall from the sky, trust that it will unfold exactly as you need it to. Do not seek for other people's approval. Have faith in yourself—just believe in you, only you.

* Introspection 2

Second, don’t place any value on others' judgments or beliefs about you. Many people, even those close to you or even family, may try to elevate themselves by doubting your path, time and efforts. Look them in the eye, smile, and recognize how small-minded they must be to focus on saying something about you that they don't really know about without understanding your journey. Remember, no words you say can change who they are, so silence is the best response.

* Introspection 3

Third, picture yourself existing on an environment which does not allow the growth of individual who aspire to go beyond the norms. Those around you prefer that you work in a job devoid of passion, performing monotonous tasks day after day. They wouldn’t care to know about what your work environment is like. Their sole concern is your ability to earn money to support them and for them to accept that you have a “work”. I'm convinced they will cease their demands once you achieve that.

