#+title: Introspectio(n)
#+author:
#+language: en
#+startup: overview
#+options: toc:nil html-postamble:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/nix.css">

[[file:../index.html][Home]]   ✾   [[file:../about.html][About]]

* Introspection 1  
First. Believe in yourself. Remember that you are building a future and be part of an organization that's going to shape the way people all live, and think that, “If someone can be part of 1%, you can too.” whether the path ahead seems crumbling, challenging, or even the ground cracks open, or rocks fall from the sky, trust that it will unfold exactly as you need it to. Do not seek for other people's approval. Have faith in yourself—just believe in you, only you.

* Introspection 2
Second. Don’t place any value on others' judgments or beliefs about you. Many people, even those close to you or even family, may try to elevate themselves by doubting your path, time and efforts. Look them in the eye, smile, and recognize how small-minded they must be to focus on saying something about you that they don't really know about without understanding your journey. Remember, no words you say can change who they are, so silence is the best response.

* Introspection 3
Third. Picture yourself existing on an environment which does not allow the growth of individual who aspire to go beyond the norms. Those around you prefer that you work in a job devoid of passion, performing monotonous tasks day after day. They wouldn’t care to know about what your work environment is like. Their sole concern is your ability to earn money to support them and for them to accept that you have a “work”. I'm convinced they will cease their demands once you achieve that.

* Introspection 4
Fourth. It's hard to wait around for something you know might never happen but it's harder to give up
when you know it's everything you want.

* Introspection 5
Fifth. Once you commit to shifting into a higher reality, the Universe will conspire in your favor. The right opportunities will appear, and the right people will show up—but not until you fully commit to the path. Once you do, that's when the real magic begins

* Introspection 6
Sixth. Everyone you meet always asks if you have a career, are in relationship or own something as if life was some kind of grocery list but nobody ever asks if you are okay or are happy.

* Introspection 7
Seventh. To attract better, you have to become better. You can't do the same things and expect change. Transform your mindset. Upgrade your habits. Think positive. Be hopeful and consistent with your evolution. It all starts with you and how you feel about yourself.

* Introspection 8
Eight. Discipline is explaining to your brain that you need to sacrifice immediate pleasures for greater rewards in the future.

* Introspection 9
Ninth. Some people stop because it's hard, some people start because it's hard.

* Introspection 10
Tenth. In order to be irreplaceable, one must always be different.
